### PR TITLE
6 crud functionalities for videos

### LINKED ISSUE #6: [backend][feature] CRUD Functionalities For Videos
- [x] I have searched the [issues](https://github.com/kzkaneoka/reddit-short-videos/issues) of this repository and believe that this is not a duplicate.

## Description 🎨

- CRUD functionalities for videos such as
  - GET
  - POST
  - PUT
  - DELETE

## Note 📑✏

- Need to work with authentication & authorization after implementing auth functionalities as well.

### PR DESCRIPTION
**Pull request by kzkaneoka**
## Description

Implemented CRUD functionalities for videos.

- GET api/v1/videos
- GET api/v1/videos/:id
- POST api/v1/videos
- PUT api/v1/videos/:id
- DELETE api/v1/videos/:id

## How Has This Been Tested?

For now, I tested them manually.

- [x] Tested each APIs mentioned above with CORRECT parameters and body.
- [x] Tested each APIs mentioned above with INCORRECT parameters and body.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by kzkaneoka** [comment]
Can someone have a light check? Thanks.

**Review by sujeongy — APPROVED** [review]
Checked 👍🏻

**Comment by kzkaneoka** [comment]
> Checked 👍🏻

Arigato-gozaimasu :)

**Comment by kzkaneoka** [comment]
@KrystalY could you merge it when you have time? thanks

**Comment by sujeongy** [comment]
no one did merge. so just do now

**Pull request merged**
